import { getToken } from "@vercel/connect";
import { Octokit } from "@octokit/rest";
import { createHmac } from "node:crypto";
import type { DeepsecOutbox } from "@/config/schema";
import type { RepositoryConfig } from "@/config/schema";

function connector(): string {
  const value = process.env.GITHUB_CONNECTOR;
  if (!value) throw new Error("GITHUB_CONNECTOR is not configured");
  return value;
}

export async function getGitHubInstallationToken(
  repository: string,
  permissions: Array<"contents:read" | "issues:write">,
): Promise<string> {
  try {
    return await getToken(
      connector(),
      {
        subject: { type: "app" },
        authorizationDetails: [
          { type: "github_app_installation", repositories: [repository], permissions },
        ],
      },
      process.env.VERCEL_TOKEN
        ? { vercelToken: process.env.VERCEL_TOKEN }
        : undefined,
    );
  } catch {
    // Connector errors are controlled by an external SDK and may carry request
    // metadata. Keep Workflow failures useful without reflecting credentials.
    throw new Error("Could not obtain a repository-scoped GitHub connector token");
  }
}

function marker(repoId: string, sha: string): string {
  const secret = process.env.DEEPSEC_MARKER_SECRET;
  if (!secret) throw new Error("DEEPSEC_MARKER_SECRET is not configured");
  const digest = createHmac("sha256", secret)
    .update(`${repoId}:${sha}`)
    .digest("hex");
  return `<!-- deepsec-runner:${digest} -->`;
}

export async function publishGitHubIssue(
  config: RepositoryConfig,
  outbox: DeepsecOutbox,
  workflowRunId: string,
  sandboxName: string,
): Promise<{ issueUrl?: string; action: "created" | "updated" | "skipped" }> {
  if (outbox.status !== "findings") return { action: "skipped" };
  if (config.issuePublication === "slack-only") return { action: "skipped" };

  const hiddenMarker = marker(config.id, outbox.targetSha);
  const token = await getGitHubInstallationToken(config.repository, ["issues:write"]);
  const [owner, repo] = config.repository.split("/") as [string, string];
  const title = `[deepsec] Findings at ${outbox.targetSha.slice(0, 12)}`;
  const body = [
    hiddenMarker,
    "## deepsec incremental analysis",
    "",
    `- Repository: \`${config.repository}\``,
    `- Branch: \`${outbox.branch}\``,
    `- Compared: \`${outbox.baseSha?.slice(0, 12) ?? "full baseline"}\` → \`${outbox.targetSha.slice(0, 12)}\``,
    `- Files investigated: ${outbox.files.length}`,
    `- Run mode: \`${outbox.mode}\``,
    `- Model: \`${config.agent}/${config.model}\` (${config.thinkingLevel})`,
    `- Workflow run: \`${workflowRunId}\``,
    `- Persistent Sandbox: \`${sandboxName}\``,
    `- Completed: ${outbox.completedAt}`,
    "",
    outbox.summary,
    "",
    "_Generated by the deepsec runner. Validate exploitability before remediation. Sandbox names are operational identifiers; Sandboxes are private and are not public URLs._",
  ].join("\n").slice(0, 65_000);

  try {
    const octokit = new Octokit({ auth: token });
    const identity = await octokit.graphql<{ viewer: { login: string } }>(
      "query deepsecPublisherIdentity { viewer { login } }",
    );
    const existing = await octokit.paginate(octokit.rest.issues.listForRepo, {
      owner,
      repo,
      state: "all",
      per_page: 100,
    });
    const match = existing.find(
      (issue) =>
        !issue.pull_request &&
        issue.user?.login === identity.viewer.login &&
        issue.body?.includes(hiddenMarker),
    );

    if (match) {
      const updated = await octokit.rest.issues.update({
        owner,
        repo,
        issue_number: match.number,
        title,
        body,
        state: "open",
      });
      return { action: "updated", issueUrl: updated.data.html_url };
    }

    const created = await octokit.rest.issues.create({ owner, repo, title, body });
    return { action: "created", issueUrl: created.data.html_url };
  } catch {
    // Octokit errors may include request headers. Do not let a connector token
    // become part of durable Workflow failure state or a Slack notification.
    throw new Error("GitHub issue publication failed");
  }
}
